<a href="https://colab.research.google.com/github/Mehaksaluja/NumPy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import numpy as np

In [61]:
crr = np.array([1,2,3],dtype='float')
print(crr)

[1. 2. 3.]


In [62]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [63]:
#2d array
b = np.array([[1,2,3],[4,5,6]])
print(arr)
b.ndim #tells the dimention of array
b.dtype #tells the datatype of array

[1 2 3]


dtype('int64')

In [64]:
#3d array
a = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [65]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [67]:
# with reshape
np.arange(1,11).reshape(2,5)
# here 2 is rows & 5 is columns
# as there were 10 columns in it ,
# so we can only give the number which give 10 on multiplication

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [68]:
# np.ones
np.ones((3,4))
# To make the matrix whose dimentions are 3*4 & all elements are one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
# np.zeros
np.zeros((3,2))
# To make the matrix whose dimentions are 3*2 & all elements are zero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [70]:
# np.random
np.random.random((3,4))
# give random numbers array


array([[0.74060598, 0.64735332, 0.85711368, 0.95040938],
       [0.17562537, 0.30673244, 0.84018197, 0.26500348],
       [0.85080476, 0.77030266, 0.35701669, 0.7649487 ]])

In [71]:
# np.linspace
np.linspace(-10,10,8)
# generate 10 numbers between 10 and -10 with equal spaces between two

array([-10.        ,  -7.14285714,  -4.28571429,  -1.42857143,
         1.42857143,   4.28571429,   7.14285714,  10.        ])

In [72]:
# np.identity
np.identity(3)
# generate identity matrix of 3 X 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes



In [73]:
a1 = np.arange(10)
a2 = np.arange(12,dtype = float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [74]:
a1.ndim #ndim tells dimention of array

1

In [75]:
a2.shape #tells the rows and columns of array

(3, 4)

In [76]:
a3.size #tells the no. of elements in array

8

In [77]:
a3.itemsize #bits taken

8

In [78]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [79]:
# changing datatype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [80]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [81]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
# scalar operations
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [84]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [85]:
# vector operations
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array Functions

In [86]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[22., 15., 21.],
       [25., 40., 24.],
       [41.,  1., 60.]])

In [87]:
# max/min/sum/prod
np.max(a1)
# np.min(a1)= 0 -> col , 1 -> row

60.0

In [88]:
np.max(a1,axis = 0)

array([41., 40., 60.])

In [89]:
# mean/median/std/var
np.mean(a1)

27.666666666666668

In [90]:
np.sin(a1)

array([[-0.00885131,  0.65028784,  0.83665564],
       [-0.13235175,  0.74511316, -0.90557836],
       [-0.15862267,  0.84147098, -0.30481062]])

In [91]:
# dot product
a2 = np.arange(10).reshape(2,5)
a3 = np.arange(5).reshape(5,1)
np.dot(a2,a3)

array([[30],
       [80]])

In [92]:
# log & exponents
np.log(a1)

array([[3.09104245, 2.7080502 , 3.04452244],
       [3.21887582, 3.68887945, 3.17805383],
       [3.71357207, 0.        , 4.09434456]])

In [93]:
# round/floor/ceil
np.round(np.random.random((3,3))*100)

array([[77., 80., 96.],
       [43., 53., 46.],
       [18., 75., 90.]])

Indexing & Slicing

In [94]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [95]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
# if we want to find 6 using indexing thwn we write it like this
a2[1,2]

6

In [97]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
# as a3 is 3d array then if we want to find 5 in a3 then we do like this
a3[1,0,1]

5

In [99]:
# slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
a1[2:5]

array([2, 3, 4])

In [101]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
a2[:,2]

array([ 2,  6, 10])

In [103]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [104]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [105]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [106]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
a2[1,::3]

array([4, 7])

In [108]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [109]:
# a3
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [110]:
a3[1,:,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [111]:
a3[0,1,:]

array([3, 4, 5])

In [112]:
a3[1,:,1]

array([10, 13, 16])

In [113]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [114]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [116]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [117]:
# Print all elements of any other dimension array except 1D
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [118]:
# Transpose[Transpose means all rows becomes columns and all columns become rows]
np.transpose(a2)
# Instead of writing Transpose we can also write (np.T)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [119]:
# ravel [Converts any dimentional array into 1D Array]
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [123]:
# Stacking means adding two arrays into one
# They can be done -> horizontally or -> vertically
# Let's create two arrays a4 and a5
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [124]:
np.hstack((a4,a5)) #here hstack is horizontal stack

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [125]:
np.vstack((a4,a5)) #here vstack is vertical stack

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [126]:
# Splitting is opposite to stack , in this we slipt array into number of equal parts
# It can also be done horizontally and vertically
np.hsplit(a4,2) #here to represents two equal halfs

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [129]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]